# Generated by Django 4.1.1 on 2022-09-23 06:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_studentcoursemapping_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, through='api.StudentCourseMapping', to='api.course'),
        ),
        migrations.AlterField(
            model_name='studentcoursemapping',
            name='score',
            field=models.PositiveIntegerField(validators=[api.models.validate_score]),
        ),
    ]
